# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMouseTracking(True)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuOpen_Recent = QtWidgets.QMenu(self.menu)
        self.menuOpen_Recent.setObjectName("menuOpen_Recent")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(20, 20))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/icons8-创建新的-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/icons8-打开文件夹-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose_Window = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/icons8-关闭窗口-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose_Window.setIcon(icon2)
        self.actionClose_Window.setObjectName("actionClose_Window")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/icons8-另存为-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/icons8-复制-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon4)
        self.actionCopy.setObjectName("actionCopy")
        self.actionRename = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/icons8-重命名-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename.setIcon(icon5)
        self.actionRename.setObjectName("actionRename")
        self.actionClear_Menu = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/images/icons8-清除搜索-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_Menu.setIcon(icon6)
        self.actionClear_Menu.setObjectName("actionClear_Menu")
        self.actionMoveTo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/image/images/icons8-右2-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMoveTo.setIcon(icon7)
        self.actionMoveTo.setObjectName("actionMoveTo")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/image/images/icons8-出口-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon8)
        self.actionExport.setObjectName("actionExport")
        self.actionExport_To_PDF = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/image/images/icons8-导出pdf-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_To_PDF.setIcon(icon9)
        self.actionExport_To_PDF.setObjectName("actionExport_To_PDF")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/image/images/icons8-打印-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon10)
        self.actionPrint.setObjectName("actionPrint")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/image/images/icons8-撤销-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon11)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/image/images/icons8-恢复-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon12)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/image/images/icons8-剪切-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon13)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy_2 = QtWidgets.QAction(MainWindow)
        self.actionCopy_2.setIcon(icon4)
        self.actionCopy_2.setObjectName("actionCopy_2")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/image/images/icons8-粘贴-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon14)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/image/images/icons8-删除-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon15)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/image/images/icons8-全选-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_All.setIcon(icon16)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionInsert = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/image/images/icons8-插入-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsert.setIcon(icon17)
        self.actionInsert.setObjectName("actionInsert")
        self.actionMove_To_Trash = QtWidgets.QAction(MainWindow)
        self.actionMove_To_Trash.setIcon(icon15)
        self.actionMove_To_Trash.setObjectName("actionMove_To_Trash")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/image/images/icons8-zoom-in-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon18)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/image/images/icons8-zoom-out-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon19)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionChange_Color = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/image/images/icons8-涂料调色-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChange_Color.setIcon(icon20)
        self.actionChange_Color.setObjectName("actionChange_Color")
        self.actionResize = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/image/images/icons8-调整对角线-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResize.setIcon(icon21)
        self.actionResize.setObjectName("actionResize")
        self.actionRotate_To_Left = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/image/images/icons8-向左旋转-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotate_To_Left.setIcon(icon22)
        self.actionRotate_To_Left.setObjectName("actionRotate_To_Left")
        self.actionRotate_To_Right = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/image/images/icons8-向右旋转-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotate_To_Right.setIcon(icon23)
        self.actionRotate_To_Right.setObjectName("actionRotate_To_Right")
        self.actionFlip_Horizontal = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/image/images/icons8-水平翻转-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlip_Horizontal.setIcon(icon24)
        self.actionFlip_Horizontal.setObjectName("actionFlip_Horizontal")
        self.actionFlip_Vertical = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/image/images/icons8-垂直翻转-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlip_Vertical.setIcon(icon25)
        self.actionFlip_Vertical.setObjectName("actionFlip_Vertical")
        self.actionClip = QtWidgets.QAction(MainWindow)
        self.actionClip.setIcon(icon13)
        self.actionClip.setObjectName("actionClip")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/image/images/icons8-最小化窗口-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMinimize.setIcon(icon26)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/image/images/icons8-缩小-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon27)
        self.actionZoom.setObjectName("actionZoom")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/image/images/icons8-搜索-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch.setIcon(icon28)
        self.actionSearch.setObjectName("actionSearch")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/image/images/icons8-帮助-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon29)
        self.actionHelp.setObjectName("actionHelp")
        self.actionShare = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/image/images/icons8-上传-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShare.setIcon(icon30)
        self.actionShare.setObjectName("actionShare")
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setCheckable(True)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/image/images/icons8-选择无-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect.setIcon(icon31)
        self.actionSelect.setObjectName("actionSelect")
        self.actionShape = QtWidgets.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/image/images/icons8-改变形状-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShape.setIcon(icon32)
        self.actionShape.setObjectName("actionShape")
        self.actionPattern = QtWidgets.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/image/images/icons8-行宽-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPattern.setIcon(icon33)
        self.actionPattern.setObjectName("actionPattern")
        self.actionBorder_Color = QtWidgets.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/image/images/icons8-边框颜色-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBorder_Color.setIcon(icon34)
        self.actionBorder_Color.setObjectName("actionBorder_Color")
        self.actionFill_Color = QtWidgets.QAction(MainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/image/images/icons8-填色-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFill_Color.setIcon(icon35)
        self.actionFill_Color.setObjectName("actionFill_Color")
        self.actionHide_ToolBar = QtWidgets.QAction(MainWindow)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/image/images/icons8-隐藏-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_ToolBar.setIcon(icon36)
        self.actionHide_ToolBar.setObjectName("actionHide_ToolBar")
        self.menuOpen_Recent.addSeparator()
        self.menuOpen_Recent.addAction(self.actionClear_Menu)
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.menuOpen_Recent.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actionClose_Window)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionCopy)
        self.menu.addAction(self.actionRename)
        self.menu.addAction(self.actionMoveTo)
        self.menu.addAction(self.actionExport)
        self.menu.addAction(self.actionExport_To_PDF)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPrint)
        self.menu_2.addAction(self.actionUndo)
        self.menu_2.addAction(self.actionRedo)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionCut)
        self.menu_2.addAction(self.actionCopy_2)
        self.menu_2.addAction(self.actionPaste)
        self.menu_2.addAction(self.actionDelete)
        self.menu_2.addAction(self.actionSelect_All)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionInsert)
        self.menu_2.addAction(self.actionMove_To_Trash)
        self.menu_3.addAction(self.actionHide_ToolBar)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionZoom_In)
        self.menu_3.addAction(self.actionZoom_Out)
        self.menu_4.addAction(self.actionChange_Color)
        self.menu_4.addAction(self.actionResize)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.actionRotate_To_Left)
        self.menu_4.addAction(self.actionRotate_To_Right)
        self.menu_4.addAction(self.actionFlip_Horizontal)
        self.menu_4.addAction(self.actionFlip_Vertical)
        self.menu_4.addAction(self.actionClip)
        self.menu_5.addAction(self.actionMinimize)
        self.menu_5.addAction(self.actionZoom)
        self.menu_6.addAction(self.actionHelp)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addAction(self.actionZoom_In)
        self.toolBar.addAction(self.actionShare)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRotate_To_Left)
        self.toolBar.addAction(self.actionRotate_To_Right)
        self.toolBar.addAction(self.actionFlip_Horizontal)
        self.toolBar.addAction(self.actionFlip_Vertical)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClip)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionChange_Color)
        self.toolBar.addAction(self.actionResize)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPattern)
        self.toolBar.addAction(self.actionBorder_Color)
        self.toolBar.addAction(self.actionFill_Color)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "画图"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuOpen_Recent.setTitle(_translate("MainWindow", "打开最近使用"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "显示"))
        self.menu_4.setTitle(_translate("MainWindow", "工具"))
        self.menu_5.setTitle(_translate("MainWindow", "窗口"))
        self.menu_6.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "新建"))
        self.actionNew.setStatusTip(_translate("MainWindow", "新建"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "打开"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose_Window.setText(_translate("MainWindow", "关闭窗口"))
        self.actionClose_Window.setStatusTip(_translate("MainWindow", "关闭窗口"))
        self.actionClose_Window.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSave.setText(_translate("MainWindow", "存储"))
        self.actionSave.setStatusTip(_translate("MainWindow", "存储"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCopy.setText(_translate("MainWindow", "复制"))
        self.actionCopy.setStatusTip(_translate("MainWindow", "复制"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+Shift+Num+S"))
        self.actionRename.setText(_translate("MainWindow", "重新命名..."))
        self.actionRename.setStatusTip(_translate("MainWindow", "重新命名"))
        self.actionClear_Menu.setText(_translate("MainWindow", "清除菜单"))
        self.actionClear_Menu.setStatusTip(_translate("MainWindow", "清除菜单"))
        self.actionMoveTo.setText(_translate("MainWindow", "移到..."))
        self.actionMoveTo.setStatusTip(_translate("MainWindow", "移到"))
        self.actionExport.setText(_translate("MainWindow", "导出..."))
        self.actionExport.setStatusTip(_translate("MainWindow", "导出"))
        self.actionExport_To_PDF.setText(_translate("MainWindow", "导出为PDF..."))
        self.actionExport_To_PDF.setIconText(_translate("MainWindow", "导出为PDF"))
        self.actionExport_To_PDF.setStatusTip(_translate("MainWindow", "导出为PDF"))
        self.actionPrint.setText(_translate("MainWindow", "打印"))
        self.actionPrint.setStatusTip(_translate("MainWindow", "打印"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionUndo.setText(_translate("MainWindow", "撤销"))
        self.actionUndo.setStatusTip(_translate("MainWindow", "撤销"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "重做"))
        self.actionRedo.setStatusTip(_translate("MainWindow", "重做"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Num+Z"))
        self.actionCut.setText(_translate("MainWindow", "剪切"))
        self.actionCut.setStatusTip(_translate("MainWindow", "剪切"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy_2.setText(_translate("MainWindow", "拷贝"))
        self.actionCopy_2.setStatusTip(_translate("MainWindow", "拷贝"))
        self.actionCopy_2.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "粘贴"))
        self.actionPaste.setStatusTip(_translate("MainWindow", "粘贴"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionDelete.setText(_translate("MainWindow", "删除"))
        self.actionDelete.setStatusTip(_translate("MainWindow", "删除"))
        self.actionSelect_All.setText(_translate("MainWindow", "全选"))
        self.actionSelect_All.setStatusTip(_translate("MainWindow", "全选"))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionInsert.setText(_translate("MainWindow", "插入"))
        self.actionInsert.setStatusTip(_translate("MainWindow", "插入"))
        self.actionMove_To_Trash.setText(_translate("MainWindow", "移到废纸篓"))
        self.actionMove_To_Trash.setStatusTip(_translate("MainWindow", "移到废纸篓"))
        self.actionMove_To_Trash.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.actionZoom_In.setText(_translate("MainWindow", "放大"))
        self.actionZoom_In.setStatusTip(_translate("MainWindow", "放大"))
        self.actionZoom_In.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoom_Out.setText(_translate("MainWindow", "缩小"))
        self.actionZoom_Out.setStatusTip(_translate("MainWindow", "缩小"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionChange_Color.setText(_translate("MainWindow", "调整颜色"))
        self.actionChange_Color.setStatusTip(_translate("MainWindow", "调整颜色"))
        self.actionChange_Color.setShortcut(_translate("MainWindow", "Ctrl+Alt+C"))
        self.actionResize.setText(_translate("MainWindow", "调整大小"))
        self.actionResize.setStatusTip(_translate("MainWindow", "调整大小"))
        self.actionRotate_To_Left.setText(_translate("MainWindow", "向左旋转"))
        self.actionRotate_To_Left.setStatusTip(_translate("MainWindow", "向左旋转"))
        self.actionRotate_To_Left.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionRotate_To_Right.setText(_translate("MainWindow", "向右旋转"))
        self.actionRotate_To_Right.setStatusTip(_translate("MainWindow", "向右旋转"))
        self.actionRotate_To_Right.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionFlip_Horizontal.setText(_translate("MainWindow", "水平翻转"))
        self.actionFlip_Horizontal.setStatusTip(_translate("MainWindow", "水平翻转"))
        self.actionFlip_Vertical.setText(_translate("MainWindow", "垂直翻转"))
        self.actionFlip_Vertical.setStatusTip(_translate("MainWindow", "垂直翻转"))
        self.actionClip.setText(_translate("MainWindow", "裁剪"))
        self.actionClip.setStatusTip(_translate("MainWindow", "裁剪"))
        self.actionClip.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.actionMinimize.setText(_translate("MainWindow", "最小化"))
        self.actionMinimize.setStatusTip(_translate("MainWindow", "最小化"))
        self.actionMinimize.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionZoom.setText(_translate("MainWindow", "缩放"))
        self.actionZoom.setStatusTip(_translate("MainWindow", "缩放"))
        self.actionSearch.setText(_translate("MainWindow", "搜索"))
        self.actionSearch.setStatusTip(_translate("MainWindow", "搜索"))
        self.actionHelp.setText(_translate("MainWindow", "画图帮助"))
        self.actionHelp.setStatusTip(_translate("MainWindow", "画图帮助"))
        self.actionShare.setText(_translate("MainWindow", "共享"))
        self.actionShare.setToolTip(_translate("MainWindow", "共享"))
        self.actionShare.setStatusTip(_translate("MainWindow", "共享"))
        self.actionSelect.setText(_translate("MainWindow", "选择工具"))
        self.actionSelect.setToolTip(_translate("MainWindow", "选择工具"))
        self.actionSelect.setStatusTip(_translate("MainWindow", "选择工具"))
        self.actionShape.setText(_translate("MainWindow", "形状"))
        self.actionShape.setToolTip(_translate("MainWindow", "形状"))
        self.actionShape.setStatusTip(_translate("MainWindow", "形状"))
        self.actionPattern.setText(_translate("MainWindow", "形状样式"))
        self.actionPattern.setToolTip(_translate("MainWindow", "形状样式"))
        self.actionPattern.setStatusTip(_translate("MainWindow", "形状样式"))
        self.actionBorder_Color.setText(_translate("MainWindow", "边框颜色"))
        self.actionBorder_Color.setToolTip(_translate("MainWindow", "边框颜色"))
        self.actionBorder_Color.setStatusTip(_translate("MainWindow", "边框颜色"))
        self.actionFill_Color.setText(_translate("MainWindow", "填充颜色"))
        self.actionFill_Color.setToolTip(_translate("MainWindow", "填充颜色"))
        self.actionFill_Color.setStatusTip(_translate("MainWindow", "填充颜色"))
        self.actionHide_ToolBar.setText(_translate("MainWindow", "隐藏工具栏"))

import resource_rc
