# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pen_properties_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PenPropertiesDialog(object):
    def setupUi(self, PenPropertiesDialog):
        PenPropertiesDialog.setObjectName("PenPropertiesDialog")
        PenPropertiesDialog.resize(339, 279)
        PenPropertiesDialog.setMaximumSize(QtCore.QSize(339, 279))
        PenPropertiesDialog.setSizeGripEnabled(True)
        self.layoutWidget = QtWidgets.QWidget(PenPropertiesDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(62, 41, 222, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pen_width_label = QtWidgets.QLabel(self.layoutWidget)
        self.pen_width_label.setObjectName("pen_width_label")
        self.horizontalLayout_2.addWidget(self.pen_width_label)
        self.pen_width_slider = QtWidgets.QSlider(self.layoutWidget)
        self.pen_width_slider.setMaximum(10)
        self.pen_width_slider.setProperty("value", 2)
        self.pen_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.pen_width_slider.setObjectName("pen_width_slider")
        self.horizontalLayout_2.addWidget(self.pen_width_slider)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.pen_width_spin_box = QtWidgets.QSpinBox(self.layoutWidget)
        self.pen_width_spin_box.setMaximum(10)
        self.pen_width_spin_box.setProperty("value", 2)
        self.pen_width_spin_box.setObjectName("pen_width_spin_box")
        self.horizontalLayout_5.addWidget(self.pen_width_spin_box)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pen_style_label = QtWidgets.QLabel(self.layoutWidget)
        self.pen_style_label.setObjectName("pen_style_label")
        self.horizontalLayout.addWidget(self.pen_style_label)
        self.pen_style_combo_box = QtWidgets.QComboBox(self.layoutWidget)
        self.pen_style_combo_box.setObjectName("pen_style_combo_box")
        self.pen_style_combo_box.addItem("")
        self.pen_style_combo_box.addItem("")
        self.pen_style_combo_box.addItem("")
        self.pen_style_combo_box.addItem("")
        self.pen_style_combo_box.addItem("")
        self.horizontalLayout.addWidget(self.pen_style_combo_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cap_style_label = QtWidgets.QLabel(self.layoutWidget)
        self.cap_style_label.setObjectName("cap_style_label")
        self.horizontalLayout_3.addWidget(self.cap_style_label)
        self.cap_style_combo_box = QtWidgets.QComboBox(self.layoutWidget)
        self.cap_style_combo_box.setObjectName("cap_style_combo_box")
        self.cap_style_combo_box.addItem("")
        self.cap_style_combo_box.addItem("")
        self.cap_style_combo_box.addItem("")
        self.horizontalLayout_3.addWidget(self.cap_style_combo_box)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.join_style_label = QtWidgets.QLabel(self.layoutWidget)
        self.join_style_label.setObjectName("join_style_label")
        self.horizontalLayout_4.addWidget(self.join_style_label)
        self.join_style_combo_box = QtWidgets.QComboBox(self.layoutWidget)
        self.join_style_combo_box.setObjectName("join_style_combo_box")
        self.join_style_combo_box.addItem("")
        self.join_style_combo_box.addItem("")
        self.join_style_combo_box.addItem("")
        self.horizontalLayout_4.addWidget(self.join_style_combo_box)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.pen_width_label.setBuddy(self.pen_width_slider)
        self.pen_style_label.setBuddy(self.pen_style_combo_box)
        self.cap_style_label.setBuddy(self.cap_style_combo_box)
        self.join_style_label.setBuddy(self.join_style_combo_box)

        self.retranslateUi(PenPropertiesDialog)
        self.buttonBox.accepted.connect(PenPropertiesDialog.accept)
        self.buttonBox.rejected.connect(PenPropertiesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PenPropertiesDialog)

    def retranslateUi(self, PenPropertiesDialog):
        _translate = QtCore.QCoreApplication.translate
        PenPropertiesDialog.setWindowTitle(_translate("PenPropertiesDialog", "画笔属性"))
        self.pen_width_label.setText(_translate("PenPropertiesDialog", "&Pen Width:"))
        self.pen_style_label.setText(_translate("PenPropertiesDialog", "Pen Style:"))
        self.pen_style_combo_box.setCurrentText(_translate("PenPropertiesDialog", "SolidLine"))
        self.pen_style_combo_box.setItemText(0, _translate("PenPropertiesDialog", "SolidLine"))
        self.pen_style_combo_box.setItemText(1, _translate("PenPropertiesDialog", "DashLine"))
        self.pen_style_combo_box.setItemText(2, _translate("PenPropertiesDialog", "DotLine"))
        self.pen_style_combo_box.setItemText(3, _translate("PenPropertiesDialog", "DashDotLine"))
        self.pen_style_combo_box.setItemText(4, _translate("PenPropertiesDialog", "DashDotDotLine"))
        self.cap_style_label.setText(_translate("PenPropertiesDialog", "Cap Style:"))
        self.cap_style_combo_box.setItemText(0, _translate("PenPropertiesDialog", "SquareCap"))
        self.cap_style_combo_box.setItemText(1, _translate("PenPropertiesDialog", "FlatCap"))
        self.cap_style_combo_box.setItemText(2, _translate("PenPropertiesDialog", "RoundCap"))
        self.join_style_label.setText(_translate("PenPropertiesDialog", "Join Style:"))
        self.join_style_combo_box.setItemText(0, _translate("PenPropertiesDialog", "BevelJoin"))
        self.join_style_combo_box.setItemText(1, _translate("PenPropertiesDialog", "MiterJoin"))
        self.join_style_combo_box.setItemText(2, _translate("PenPropertiesDialog", "RoundJoin"))

